title: 'Henrique Laureano'
logo: './laurence2.png'
description: 'Data Science, Forecasting, and AI Engineering @EBANX'
email: 'henriqueaparecidolaureano |at| gmail |dot| com'
twitter: '@hap_laureano'
theme: jekyll-theme-minimal
